version: '3.4'

networks:
   frontend:
   backend:

services:
   event:
      image: events/eventapi
      build:
         context: .\ProjectEventApi
         dockerfile: Dockerfile
      environment:
         DatabaseServer: mssqlserver
         DatabaseName: EventDb
         DatabaseUser: sa
         DatabasePassword: ProductApi(83)
         ExternalEventBaseUrl: http://localhost:6900
      ports: 
         - "6900:80"
      container_name: eventseventapi
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver

   mssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      environment:
         ACCEPT_EULA: Y
         SA_PASSWORD: ProductApi(83)
      ports:
         - "1449:1433"
      container_name: eventssqlserver
      networks:
         - backend
         
   webmvc:
     build:
       context: .\webmvc
       dockerfile: Dockerfile
     image: hubs/webmvc
     container_name: eventhub
     environment:
       CatalogUrl: http://event
       ASPNETCORE_ENVIRONMENT: Development
     ports:
       - "5310:80"
     networks:
       - frontend
     depends_on:
       - event  
  
